### ISSUE TITLE
atm importing issue

### ISSUE THREAD

**Issue by cici-tan** [HDI-Project/ATM#50]
When I run atm/enter_data.py, it pops up this error:
ImportError: No module named atm.config

**Comment by bcyphers** [comment]
Thanks for finding this. This was an issue with `future` being required for the newest version of btb, but not being installed. Should be fixed now.

**Comment by cici-tan** [comment]
thx, fixed now.

**Comment by Suzuki-Takatomo** [comment]
I experienced the same situation.
but I don't know how to re-install btb...
Please tell me how to re-install it in detail.

**Comment by bcyphers** [comment]
Copying the line from the `requirements.txt` should do it: 
```
pip install -e git+https://github.com/hdi-project/btb.git#egg=btb
```

**Comment by Suzuki-Takatomo** [comment]
thanks.
I tried it  but, atm/enter_data.py didn't work... 
Is this type of error different from hers?

---------------------------------------------------------
Traceback (most recent call last):
  File "atm/enter_data.py", line 10, in <module>
    from atm.config import *
ModuleNotFoundError: No module named 'atm'

**Comment by bcyphers** [comment]
Can you paste the output from
```
python --version
```
and 
```
pip freeze
```

**Comment by Suzuki-Takatomo** [comment]
Oh, sorry ...
I  ran atm/enter_data.py on another kernel(python 3.6.4).
So it worked well on the kernel(python 2.7).
Thank you very much!

**Comment by csala** [comment]
Hello @beevabeeva 

Since the error message is not exactly the same as the one reported in this issue and this one is already closed, would you mind opening a new issue to be able to assist you about this in a cleaner context?

Please report there all the details that you can about your environment and the commands that you executed until you got the error:
* Operative System
* Python version
* virtualenv setup (if any)
* installation commands
* commands run that provoke the error

**Comment by beevabeeva** [comment]
Hi @csala ,

thanks for your reply!

I was using Kali (lol) so I'm giving it another go using CentOS 7. 
I will open a new issue if the error returns.

thanks
